/********************************************************************************
** Form generated from reading UI file 'approx.ui'
**
** Created by: Qt User Interface Compiler version 5.2.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_APPROX_H
#define UI_APPROX_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Approx
{
public:
    QWidget *centralWidget;
    QPushButton *openButton;
    QWidget *plotWidget;
    QTableWidget *inputTable;
    QLineEdit *sepEdit;
    QLabel *label;
    QLineEdit *maxitsEdit;
    QLabel *label_13;
    QLabel *label_15;
    QLabel *label_14;
    QLabel *label_12;
    QLabel *label_16;
    QLineEdit *diffstepEdit;
    QLineEdit *epsfEdit;
    QLineEdit *epsxEdit;
    QTableWidget *outputTable;
    QLabel *label_2;
    QLabel *label_3;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *Approx)
    {
        if (Approx->objectName().isEmpty())
            Approx->setObjectName(QStringLiteral("Approx"));
        Approx->resize(835, 533);
        centralWidget = new QWidget(Approx);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        openButton = new QPushButton(centralWidget);
        openButton->setObjectName(QStringLiteral("openButton"));
        openButton->setGeometry(QRect(30, 10, 141, 23));
        plotWidget = new QWidget(centralWidget);
        plotWidget->setObjectName(QStringLiteral("plotWidget"));
        plotWidget->setGeometry(QRect(10, 210, 791, 251));
        inputTable = new QTableWidget(centralWidget);
        if (inputTable->columnCount() < 60)
            inputTable->setColumnCount(60);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(7, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(8, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(9, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(10, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(11, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(12, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(13, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(14, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(15, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(16, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(17, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(18, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(19, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(20, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(21, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(22, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(23, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(24, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(25, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(26, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(27, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(28, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(29, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(30, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(31, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(32, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(33, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(34, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(35, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(36, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(37, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(38, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(39, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(40, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(41, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(42, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(43, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(44, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(45, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(46, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(47, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(48, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        inputTable->setHorizontalHeaderItem(49, __qtablewidgetitem49);
        if (inputTable->rowCount() < 1)
            inputTable->setRowCount(1);
        QBrush brush(QColor(209, 209, 209, 255));
        brush.setStyle(Qt::NoBrush);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        __qtablewidgetitem50->setBackground(brush);
        inputTable->setItem(0, 50, __qtablewidgetitem50);
        QFont font;
        font.setBold(false);
        font.setWeight(50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        __qtablewidgetitem51->setFont(font);
        inputTable->setItem(0, 58, __qtablewidgetitem51);
        inputTable->setObjectName(QStringLiteral("inputTable"));
        inputTable->setGeometry(QRect(10, 120, 801, 81));
        inputTable->setSizeIncrement(QSize(0, 0));
        inputTable->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        inputTable->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContents);
        inputTable->setEditTriggers(QAbstractItemView::NoEditTriggers);
        inputTable->setDefaultDropAction(Qt::CopyAction);
        inputTable->setSortingEnabled(true);
        inputTable->setRowCount(1);
        inputTable->setColumnCount(60);
        inputTable->horizontalHeader()->setDefaultSectionSize(40);
        sepEdit = new QLineEdit(centralWidget);
        sepEdit->setObjectName(QStringLiteral("sepEdit"));
        sepEdit->setGeometry(QRect(270, 10, 61, 20));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(200, 10, 61, 16));
        maxitsEdit = new QLineEdit(centralWidget);
        maxitsEdit->setObjectName(QStringLiteral("maxitsEdit"));
        maxitsEdit->setGeometry(QRect(760, 60, 41, 20));
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(710, 30, 46, 16));
        QFont font1;
        font1.setPointSize(10);
        label_13->setFont(font1);
        label_13->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(540, 60, 31, 16));
        label_15->setFont(font1);
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(540, 30, 31, 20));
        label_14->setFont(font1);
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(540, 0, 171, 16));
        label_12->setFont(font1);
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(655, 60, 101, 20));
        label_16->setFont(font1);
        label_16->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        diffstepEdit = new QLineEdit(centralWidget);
        diffstepEdit->setObjectName(QStringLiteral("diffstepEdit"));
        diffstepEdit->setGeometry(QRect(760, 30, 41, 20));
        epsfEdit = new QLineEdit(centralWidget);
        epsfEdit->setObjectName(QStringLiteral("epsfEdit"));
        epsfEdit->setGeometry(QRect(580, 30, 61, 20));
        epsxEdit = new QLineEdit(centralWidget);
        epsxEdit->setObjectName(QStringLiteral("epsxEdit"));
        epsxEdit->setGeometry(QRect(580, 60, 61, 20));
        outputTable = new QTableWidget(centralWidget);
        if (outputTable->columnCount() < 60)
            outputTable->setColumnCount(60);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(0, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(1, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(2, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(3, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(4, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(5, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(6, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(7, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(8, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(9, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(10, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(11, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(12, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(13, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(14, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(15, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(16, __qtablewidgetitem68);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(17, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(18, __qtablewidgetitem70);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(19, __qtablewidgetitem71);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(20, __qtablewidgetitem72);
        QTableWidgetItem *__qtablewidgetitem73 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(21, __qtablewidgetitem73);
        QTableWidgetItem *__qtablewidgetitem74 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(22, __qtablewidgetitem74);
        QTableWidgetItem *__qtablewidgetitem75 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(23, __qtablewidgetitem75);
        QTableWidgetItem *__qtablewidgetitem76 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(24, __qtablewidgetitem76);
        QTableWidgetItem *__qtablewidgetitem77 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(25, __qtablewidgetitem77);
        QTableWidgetItem *__qtablewidgetitem78 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(26, __qtablewidgetitem78);
        QTableWidgetItem *__qtablewidgetitem79 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(27, __qtablewidgetitem79);
        QTableWidgetItem *__qtablewidgetitem80 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(28, __qtablewidgetitem80);
        QTableWidgetItem *__qtablewidgetitem81 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(29, __qtablewidgetitem81);
        QTableWidgetItem *__qtablewidgetitem82 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(30, __qtablewidgetitem82);
        QTableWidgetItem *__qtablewidgetitem83 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(31, __qtablewidgetitem83);
        QTableWidgetItem *__qtablewidgetitem84 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(32, __qtablewidgetitem84);
        QTableWidgetItem *__qtablewidgetitem85 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(33, __qtablewidgetitem85);
        QTableWidgetItem *__qtablewidgetitem86 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(34, __qtablewidgetitem86);
        QTableWidgetItem *__qtablewidgetitem87 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(35, __qtablewidgetitem87);
        QTableWidgetItem *__qtablewidgetitem88 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(36, __qtablewidgetitem88);
        QTableWidgetItem *__qtablewidgetitem89 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(37, __qtablewidgetitem89);
        QTableWidgetItem *__qtablewidgetitem90 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(38, __qtablewidgetitem90);
        QTableWidgetItem *__qtablewidgetitem91 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(39, __qtablewidgetitem91);
        QTableWidgetItem *__qtablewidgetitem92 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(40, __qtablewidgetitem92);
        QTableWidgetItem *__qtablewidgetitem93 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(41, __qtablewidgetitem93);
        QTableWidgetItem *__qtablewidgetitem94 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(42, __qtablewidgetitem94);
        QTableWidgetItem *__qtablewidgetitem95 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(43, __qtablewidgetitem95);
        QTableWidgetItem *__qtablewidgetitem96 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(44, __qtablewidgetitem96);
        QTableWidgetItem *__qtablewidgetitem97 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(45, __qtablewidgetitem97);
        QTableWidgetItem *__qtablewidgetitem98 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(46, __qtablewidgetitem98);
        QTableWidgetItem *__qtablewidgetitem99 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(47, __qtablewidgetitem99);
        QTableWidgetItem *__qtablewidgetitem100 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(48, __qtablewidgetitem100);
        QTableWidgetItem *__qtablewidgetitem101 = new QTableWidgetItem();
        outputTable->setHorizontalHeaderItem(49, __qtablewidgetitem101);
        if (outputTable->rowCount() < 1)
            outputTable->setRowCount(1);
        QBrush brush1(QColor(209, 209, 209, 255));
        brush1.setStyle(Qt::NoBrush);
        QTableWidgetItem *__qtablewidgetitem102 = new QTableWidgetItem();
        __qtablewidgetitem102->setBackground(brush1);
        outputTable->setItem(0, 50, __qtablewidgetitem102);
        QTableWidgetItem *__qtablewidgetitem103 = new QTableWidgetItem();
        __qtablewidgetitem103->setFont(font);
        outputTable->setItem(0, 58, __qtablewidgetitem103);
        outputTable->setObjectName(QStringLiteral("outputTable"));
        outputTable->setGeometry(QRect(120, 40, 401, 71));
        outputTable->setSizeIncrement(QSize(0, 0));
        outputTable->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContents);
        outputTable->setEditTriggers(QAbstractItemView::NoEditTriggers);
        outputTable->setDefaultDropAction(Qt::CopyAction);
        outputTable->setSortingEnabled(true);
        outputTable->setRowCount(1);
        outputTable->setColumnCount(60);
        outputTable->horizontalHeader()->setDefaultSectionSize(40);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(60, 40, 51, 21));
        QFont font2;
        font2.setPointSize(12);
        label_2->setFont(font2);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 90, 51, 21));
        label_3->setFont(font2);
        Approx->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(Approx);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 835, 21));
        Approx->setMenuBar(menuBar);
        mainToolBar = new QToolBar(Approx);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        Approx->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(Approx);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        Approx->setStatusBar(statusBar);

        retranslateUi(Approx);

        QMetaObject::connectSlotsByName(Approx);
    } // setupUi

    void retranslateUi(QMainWindow *Approx)
    {
        Approx->setWindowTitle(QApplication::translate("Approx", "Approx", 0));
        openButton->setText(QApplication::translate("Approx", "\320\236\321\202\320\272\321\200\321\213\321\202\321\214 \321\204\320\260\320\271\320\273", 0));
        QTableWidgetItem *___qtablewidgetitem = inputTable->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem1 = inputTable->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem2 = inputTable->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem3 = inputTable->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem4 = inputTable->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem5 = inputTable->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem6 = inputTable->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem7 = inputTable->horizontalHeaderItem(7);
        ___qtablewidgetitem7->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem8 = inputTable->horizontalHeaderItem(8);
        ___qtablewidgetitem8->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem9 = inputTable->horizontalHeaderItem(9);
        ___qtablewidgetitem9->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem10 = inputTable->horizontalHeaderItem(10);
        ___qtablewidgetitem10->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem11 = inputTable->horizontalHeaderItem(11);
        ___qtablewidgetitem11->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem12 = inputTable->horizontalHeaderItem(12);
        ___qtablewidgetitem12->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem13 = inputTable->horizontalHeaderItem(13);
        ___qtablewidgetitem13->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem14 = inputTable->horizontalHeaderItem(14);
        ___qtablewidgetitem14->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem15 = inputTable->horizontalHeaderItem(15);
        ___qtablewidgetitem15->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem16 = inputTable->horizontalHeaderItem(16);
        ___qtablewidgetitem16->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem17 = inputTable->horizontalHeaderItem(17);
        ___qtablewidgetitem17->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem18 = inputTable->horizontalHeaderItem(18);
        ___qtablewidgetitem18->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem19 = inputTable->horizontalHeaderItem(19);
        ___qtablewidgetitem19->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem20 = inputTable->horizontalHeaderItem(20);
        ___qtablewidgetitem20->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem21 = inputTable->horizontalHeaderItem(21);
        ___qtablewidgetitem21->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem22 = inputTable->horizontalHeaderItem(22);
        ___qtablewidgetitem22->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem23 = inputTable->horizontalHeaderItem(23);
        ___qtablewidgetitem23->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem24 = inputTable->horizontalHeaderItem(24);
        ___qtablewidgetitem24->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem25 = inputTable->horizontalHeaderItem(25);
        ___qtablewidgetitem25->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem26 = inputTable->horizontalHeaderItem(26);
        ___qtablewidgetitem26->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem27 = inputTable->horizontalHeaderItem(27);
        ___qtablewidgetitem27->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem28 = inputTable->horizontalHeaderItem(28);
        ___qtablewidgetitem28->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem29 = inputTable->horizontalHeaderItem(29);
        ___qtablewidgetitem29->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem30 = inputTable->horizontalHeaderItem(30);
        ___qtablewidgetitem30->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem31 = inputTable->horizontalHeaderItem(31);
        ___qtablewidgetitem31->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem32 = inputTable->horizontalHeaderItem(32);
        ___qtablewidgetitem32->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem33 = inputTable->horizontalHeaderItem(33);
        ___qtablewidgetitem33->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem34 = inputTable->horizontalHeaderItem(34);
        ___qtablewidgetitem34->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem35 = inputTable->horizontalHeaderItem(35);
        ___qtablewidgetitem35->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem36 = inputTable->horizontalHeaderItem(36);
        ___qtablewidgetitem36->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem37 = inputTable->horizontalHeaderItem(37);
        ___qtablewidgetitem37->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem38 = inputTable->horizontalHeaderItem(38);
        ___qtablewidgetitem38->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem39 = inputTable->horizontalHeaderItem(39);
        ___qtablewidgetitem39->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem40 = inputTable->horizontalHeaderItem(40);
        ___qtablewidgetitem40->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem41 = inputTable->horizontalHeaderItem(41);
        ___qtablewidgetitem41->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem42 = inputTable->horizontalHeaderItem(42);
        ___qtablewidgetitem42->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem43 = inputTable->horizontalHeaderItem(43);
        ___qtablewidgetitem43->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem44 = inputTable->horizontalHeaderItem(44);
        ___qtablewidgetitem44->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem45 = inputTable->horizontalHeaderItem(45);
        ___qtablewidgetitem45->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem46 = inputTable->horizontalHeaderItem(46);
        ___qtablewidgetitem46->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem47 = inputTable->horizontalHeaderItem(47);
        ___qtablewidgetitem47->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem48 = inputTable->horizontalHeaderItem(48);
        ___qtablewidgetitem48->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem49 = inputTable->horizontalHeaderItem(49);
        ___qtablewidgetitem49->setText(QApplication::translate("Approx", "5", 0));

        const bool __sortingEnabled = inputTable->isSortingEnabled();
        inputTable->setSortingEnabled(false);
        inputTable->setSortingEnabled(__sortingEnabled);

        sepEdit->setText(QApplication::translate("Approx", ";", 0));
        label->setText(QApplication::translate("Approx", "Separator", 0));
        maxitsEdit->setText(QApplication::translate("Approx", "0", 0));
        label_13->setText(QApplication::translate("Approx", "\320\250\320\260\320\263", 0));
        label_15->setText(QApplication::translate("Approx", "epsx:", 0));
        label_14->setText(QApplication::translate("Approx", "epsf:", 0));
        label_12->setText(QApplication::translate("Approx", "\320\237\320\260\321\200\320\260\320\274\320\265\321\202\321\200\321\213 \320\260\320\277\320\277\321\200\320\276\320\272\321\201\320\270\320\274\320\260\321\206\320\270\320\270:", 0));
        label_16->setText(QApplication::translate("Approx", "\320\247\320\270\321\201\320\273\320\276 \320\270\321\202\320\265\321\200\320\260\321\206\320\270\320\271", 0));
        diffstepEdit->setText(QApplication::translate("Approx", "0.0001", 0));
        epsfEdit->setText(QApplication::translate("Approx", "0", 0));
        epsxEdit->setText(QApplication::translate("Approx", "0.000001", 0));
        QTableWidgetItem *___qtablewidgetitem50 = outputTable->horizontalHeaderItem(0);
        ___qtablewidgetitem50->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem51 = outputTable->horizontalHeaderItem(1);
        ___qtablewidgetitem51->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem52 = outputTable->horizontalHeaderItem(2);
        ___qtablewidgetitem52->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem53 = outputTable->horizontalHeaderItem(3);
        ___qtablewidgetitem53->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem54 = outputTable->horizontalHeaderItem(4);
        ___qtablewidgetitem54->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem55 = outputTable->horizontalHeaderItem(5);
        ___qtablewidgetitem55->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem56 = outputTable->horizontalHeaderItem(6);
        ___qtablewidgetitem56->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem57 = outputTable->horizontalHeaderItem(7);
        ___qtablewidgetitem57->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem58 = outputTable->horizontalHeaderItem(8);
        ___qtablewidgetitem58->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem59 = outputTable->horizontalHeaderItem(9);
        ___qtablewidgetitem59->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem60 = outputTable->horizontalHeaderItem(10);
        ___qtablewidgetitem60->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem61 = outputTable->horizontalHeaderItem(11);
        ___qtablewidgetitem61->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem62 = outputTable->horizontalHeaderItem(12);
        ___qtablewidgetitem62->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem63 = outputTable->horizontalHeaderItem(13);
        ___qtablewidgetitem63->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem64 = outputTable->horizontalHeaderItem(14);
        ___qtablewidgetitem64->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem65 = outputTable->horizontalHeaderItem(15);
        ___qtablewidgetitem65->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem66 = outputTable->horizontalHeaderItem(16);
        ___qtablewidgetitem66->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem67 = outputTable->horizontalHeaderItem(17);
        ___qtablewidgetitem67->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem68 = outputTable->horizontalHeaderItem(18);
        ___qtablewidgetitem68->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem69 = outputTable->horizontalHeaderItem(19);
        ___qtablewidgetitem69->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem70 = outputTable->horizontalHeaderItem(20);
        ___qtablewidgetitem70->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem71 = outputTable->horizontalHeaderItem(21);
        ___qtablewidgetitem71->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem72 = outputTable->horizontalHeaderItem(22);
        ___qtablewidgetitem72->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem73 = outputTable->horizontalHeaderItem(23);
        ___qtablewidgetitem73->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem74 = outputTable->horizontalHeaderItem(24);
        ___qtablewidgetitem74->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem75 = outputTable->horizontalHeaderItem(25);
        ___qtablewidgetitem75->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem76 = outputTable->horizontalHeaderItem(26);
        ___qtablewidgetitem76->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem77 = outputTable->horizontalHeaderItem(27);
        ___qtablewidgetitem77->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem78 = outputTable->horizontalHeaderItem(28);
        ___qtablewidgetitem78->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem79 = outputTable->horizontalHeaderItem(29);
        ___qtablewidgetitem79->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem80 = outputTable->horizontalHeaderItem(30);
        ___qtablewidgetitem80->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem81 = outputTable->horizontalHeaderItem(31);
        ___qtablewidgetitem81->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem82 = outputTable->horizontalHeaderItem(32);
        ___qtablewidgetitem82->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem83 = outputTable->horizontalHeaderItem(33);
        ___qtablewidgetitem83->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem84 = outputTable->horizontalHeaderItem(34);
        ___qtablewidgetitem84->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem85 = outputTable->horizontalHeaderItem(35);
        ___qtablewidgetitem85->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem86 = outputTable->horizontalHeaderItem(36);
        ___qtablewidgetitem86->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem87 = outputTable->horizontalHeaderItem(37);
        ___qtablewidgetitem87->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem88 = outputTable->horizontalHeaderItem(38);
        ___qtablewidgetitem88->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem89 = outputTable->horizontalHeaderItem(39);
        ___qtablewidgetitem89->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem90 = outputTable->horizontalHeaderItem(40);
        ___qtablewidgetitem90->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem91 = outputTable->horizontalHeaderItem(41);
        ___qtablewidgetitem91->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem92 = outputTable->horizontalHeaderItem(42);
        ___qtablewidgetitem92->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem93 = outputTable->horizontalHeaderItem(43);
        ___qtablewidgetitem93->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem94 = outputTable->horizontalHeaderItem(44);
        ___qtablewidgetitem94->setText(QApplication::translate("Approx", "5", 0));
        QTableWidgetItem *___qtablewidgetitem95 = outputTable->horizontalHeaderItem(45);
        ___qtablewidgetitem95->setText(QApplication::translate("Approx", "1", 0));
        QTableWidgetItem *___qtablewidgetitem96 = outputTable->horizontalHeaderItem(46);
        ___qtablewidgetitem96->setText(QApplication::translate("Approx", "2", 0));
        QTableWidgetItem *___qtablewidgetitem97 = outputTable->horizontalHeaderItem(47);
        ___qtablewidgetitem97->setText(QApplication::translate("Approx", "3", 0));
        QTableWidgetItem *___qtablewidgetitem98 = outputTable->horizontalHeaderItem(48);
        ___qtablewidgetitem98->setText(QApplication::translate("Approx", "4", 0));
        QTableWidgetItem *___qtablewidgetitem99 = outputTable->horizontalHeaderItem(49);
        ___qtablewidgetitem99->setText(QApplication::translate("Approx", "5", 0));

        const bool __sortingEnabled1 = outputTable->isSortingEnabled();
        outputTable->setSortingEnabled(false);
        outputTable->setSortingEnabled(__sortingEnabled1);

        label_2->setText(QApplication::translate("Approx", "Result:", 0));
        label_3->setText(QApplication::translate("Approx", "Data:", 0));
    } // retranslateUi

};

namespace Ui {
    class Approx: public Ui_Approx {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_APPROX_H
